site_name: model_coin
site_description: Its all about an earning score > 1
repo_url: https://github.com/slackerdevstudio/model-coin
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/slackerdevstudio">slackerdevstudio</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
